#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

assets="$(dirname $0)"
source "${assets}/common.sh"

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload="$(cat <&0)"

unknown_keys=$(jq --slurpfile schema "${assets}/in_schema.json" '(.params // [] | keys_unsorted) - ($schema[0] | keys_unsorted)' <<< "$payload")

if jq --exit-status 'length > 0' <<< "$unknown_keys" &>/dev/null; then
    echo "Found unknown keys in get params:"
    jq '.[]' <<< "$unknown_keys"
    exit 1
fi

src_debug=$(jq -r '.source.debug // false' <<< "$payload")
params_debug=$(jq -r '.params.debug // false' <<< "$payload")
if [[ "$src_debug" == "true" || "$params_debug" == "true" ]]; then
    echo "debug mode enabled"
    set -x
    export GIT_TRACE=1
    export GIT_TRACE_PACKFILE=1
    export GIT_CURL_VERBOSE=1
fi

git_config_payload=$(jq -r '.source.git_config // []' <<< "$payload")
configure_git_global "${git_config_payload}"
load_pubkey "$payload"
load_git_crypt_key "$payload"
configure_https_tunnel "$payload"
configure_git_ssl_verification "$payload"
setup_github_app_credentials "$payload"
configure_credentials "$payload"

# These vars are used by multiple version_type's
uri=$(jq -r '.source.uri // ""' <<< "$payload")
uri=${uri# }
if [[ -z "$uri" ]]; then
    echo "source.uri is required and must not be empty"
    exit 1
fi

version_type=$(jq -r '.source.version_type // "commits"' <<< "$payload")

case "$version_type" in
    commits)
        source "${assets}/in_commits.sh"
        ;;
    tags)
        source "${assets}/in_tags.sh"
        ;;
    branches)
        source "${assets}/in_branches.sh"
        ;;
    *)
        echo "unknown version_type: $version_type"
        exit 1
        ;;
esac
